<a href="https://colab.research.google.com/github/alexmanoel/TensorFlowExercises/blob/main/ExerciciosTensores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
# Tensores

# Tensores são a estrutura de dados primária que o TensorFlow usa para operar no grafo computacional. 
# Podemos declarar esses tensores como variáveis. 
# Quando criamos um tensor e declaramos que ele é uma variável, o TensorFlow cria várias estruturas de grafo em nosso grafo computacional.

In [7]:
# Importando os Pacotes
import tensorflow as tf
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

In [9]:
# Cria um tensor preenchido por 20 zeros, dimensão 1x20
myTensor = tf.zeros([1,20])
tf.print(myTensor)

[[0 0 0 ... 0 0 0]]


In [14]:
# Declara a variável que recebe um tensor preenchido por 20 zeros
myVar = tf.Variable(tf.zeros([1,20]))
tf.print(myVar)

[[0 0 0 ... 0 0 0]]


In [15]:
# Variáveis Python que podem ser usadas como parâmetro
row_dim = 2
col_dim = 3 

In [16]:
# Tensor inicializado com zeros usando como dimensões as variáveis criadas anteriormente
tensorZeros = tf.Variable(tf.zeros([row_dim,col_dim]))
tf.print(tensorZeros)

[[0 0 0]
 [0 0 0]]


In [21]:
# Tensor inicializado com 1's
tensorOnes = tf.Variable(tf.ones([row_dim,col_dim]))
tf.print(tensorOnes)

[[1 1 1]
 [1 1 1]]


In [22]:
# Tensor preenchido com valores constantes (variáveis Python criadas anteriormente)
tensorFill = tf.Variable(tf.fill([row_dim,col_dim], -2))
tf.print(tensorFill)

[[-2 -2 -2]
 [-2 -2 -2]]


In [23]:
# Cria um tensor a partir de uma lista de valores constantes
constTensor = tf.Variable(tf.constant([1,2,3,4,5,6]))
tf.print(constTensor)

[1 2 3 4 5 6]


In [25]:
# Similar ao anterior, mas usando variáveis Python defindas anteriormente:
myVar2 = tf.Variable(tf.constant(3, shape = [row_dim,col_dim]))
tf.print(myVar2)

[[3 3 3]
 [3 3 3]]


In [27]:
# Gerando uma sequência de valores lineares com a função tf.linspace, começando por 0.0, terminando em 1.0, com 3 elementos
tensorLin = tf.Variable(tf.linspace(0.0, 1.0, 3))
tf.print(tensorLin)

[0 0.5 1]


In [28]:
# Gerando uma sequência de valores com a função tf.range, começando por 6, limite de 15 e saltando de 3 em 3
tensorRange = tf.Variable(tf.range(start=6,limit=15,delta=3))
tf.print(tensorRange)

[6 9 12]
