<a href="https://colab.research.google.com/github/alexmanoel/TensorFlowExercises/blob/main/ExercicioMatrizesTensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# TensorFlow - Matrizes e Operações com Matrizes

# Importando os Pacotes
import numpy as np
import tensorflow as tf
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

In [29]:
# Criando uma matriz identidade 2x3
identityMatriz = tf.eye(2, num_columns=3)
print("\nMatriz Identidade")
tf.print(identityMatriz)


Matriz Identidade
[[1 0 0]
 [0 1 0]]


In [28]:
# Criando uma matriz 2x3 randomicamente normalizada
A = tf.random.truncated_normal([2,3])
print("\nMatriz A - 2x3")
tf.print(A)


Matriz A - 2x3
[[-0.0748146772 1.40461731 -0.665083766]
 [0.115781777 0.108602069 0.867733538]]


In [30]:
# Criando uma matriz 2x3 com valores constantes
B = tf.fill([2, 3], 5.0)
print("\nMatriz B - 2x3")
tf.print(B)


Matriz B - 2x3
[[5 5 5]
 [5 5 5]]


In [31]:
# Criando uma matriz 2x3 com valores randomicamente uniforme
C = tf.random.uniform([2,3])
print("\nMatriz C - 2x3")
tf.print(C)


Matriz C - 2x3
[[0.959774613 0.12152791 0.197883129]
 [0.193237901 0.998395443 0.312945604]]


In [32]:
# Convertendo um array numpy 3x3 para um tensor
array1 = np.array([[1.,2.,3.], [-3.,-7.,-1.], [0., 5., -2.]])
D = tf.convert_to_tensor(array1, dtype = tf.float64)
print("\nMatriz D - 3x3")
tf.print(D)


Matriz D - 3x3
[[1 2 3]
 [-3 -7 -1]
 [0 5 -2]]


In [36]:
# Adicione a matrix A com a Matriz B
print("\nSoma A + B")
somaMatriz = tf.math.add(A,B)
tf.print(somaMatriz)


Soma A + B
[[4.9251852 6.40461731 4.33491611]
 [5.11578178 5.10860205 5.86773348]]


In [37]:
# Subtraia a matriz B da mesma matriz B
print("\nSubtração B-B")
subMatriz = tf.math.subtract(B,B)
tf.print(subMatriz)


Subtração B-B
[[0 0 0]
 [0 0 0]]


In [38]:
# Multiplicação da Matriz A e C
print("\nMultiplicação AxC")
multMatriz = tf.math.multiply(A,C)
tf.print(multMatriz)


Multiplicação AxC
[[-0.0718052313 0.170700207 -0.131608859]
 [0.0223734267 0.108427808 0.271553397]]


In [39]:
# Transposta da matriz C
print("\nTransposta Matriz C")
transpMatriz = tf.transpose(C)
tf.print(transpMatriz)


Transposta Matriz C
[[0.959774613 0.193237901]
 [0.12152791 0.998395443]
 [0.197883129 0.312945604]]


In [40]:
# Determinante da matriz D
print("\nDeterminante Matriz D")
detMatriz = tf.linalg.det(D)
tf.print(detMatriz)


Determinante Matriz D
-37.999999999999993


In [41]:
# Matrix Inversa da matriz D
print("\nMatriz Inversa D")
invMatriz = tf.linalg.inv(D)
tf.print(invMatriz)


Matriz Inversa D
[[-0.5 -0.5 -0.5]
 [0.15789473684210528 0.052631578947368418 0.21052631578947367]
 [0.39473684210526316 0.13157894736842105 0.0263157894736842]]
